"""first revision

迁移 ID: 6ecf6db6302d
父迁移: 
创建时间: 2024-06-25 01:38:13.147086

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6ecf6db6302d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('nonebot_plugin_biliforward',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_biliforward_msginfo',
    sa.Column('msg_key', sa.Integer(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sharer_uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('msg_key', name=op.f('pk_nonebot_plugin_biliforward_msginfo')),
    info={'bind_key': 'nonebot_plugin_biliforward'}
    )
    op.create_table('nonebot_plugin_biliforward_whitelist',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('bili_user_id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'bili_user_id', name=op.f('pk_nonebot_plugin_biliforward_whitelist')),
    info={'bind_key': 'nonebot_plugin_biliforward'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_biliforward_whitelist')
    op.drop_table('nonebot_plugin_biliforward_msginfo')
    # ### end Alembic commands ###
